#!/usr/bin/env python3
"""
NHS School ERP — demo seeder.

Generates a realistic 300-student CSV (Indian school context) and pushes it
into a running backend, then sets up fee structures per class and applies
them so every student has bills + carry-forward dues to work with.

Usage:
    1. In one terminal:   py run.py            (or: python run.py)
    2. In another:        py tools/seed_demo.py

What it produces:
    - data/seed_students.csv     — the editable source file (300 rows)
    - 12 fee structures (KG1 ... 10) for academic year 2025-26
    - 300 fee bills (one per student) generated by "apply"
    - last_year_dues carried forward for ~25% of students
"""

from __future__ import annotations

import csv
import json
import os
import random
import sys
import urllib.error
import urllib.request
from datetime import date, timedelta
from pathlib import Path

# Reproducible: same script run = same data.
random.seed(20260426)

ROOT = Path(__file__).resolve().parent.parent
CSV_DIR = ROOT / "data"
CSV_PATH = CSV_DIR / "seed_students.csv"

API = os.environ.get("NHS_API", "http://127.0.0.1:8000")
OWNER_EMAIL = os.environ.get("NHS_OWNER", "owner@nagarjuna.school")
OWNER_PWD   = os.environ.get("NHS_PWD", "owner123")
EMAIL_DOMAIN = "nagarjuna.school"
DEFAULT_STUDENT_PWD = "student123"
DEFAULT_TEACHER_PWD = "teacher123"

ACADEMIC_YEAR = "2025-26"
SUBJECTS = ["English", "Hindi", "Math", "Science", "Social"]
EXAMS = [
    {"name": "Term 1",      "date": "2025-08-22"},
    {"name": "Half-yearly", "date": "2025-10-18"},
]


# ---------- Sample data ---------- #

FIRST_M = [
    "Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Reyansh","Ayaan","Krishna","Ishaan",
    "Shaurya","Atharv","Advik","Kabir","Anish","Rudra","Yug","Dhruv","Kiaan","Aryan",
    "Pranav","Rohan","Karthik","Devansh","Harsh","Yuvan","Ansh","Rishi","Veer","Akhil",
    "Vivek","Nikhil","Manav","Jay","Tanish","Aarush","Rehan","Shivansh","Kushal","Om",
]
FIRST_F = [
    "Aanya","Aaradhya","Anika","Diya","Ira","Kavya","Myra","Pari","Saanvi","Sara",
    "Tara","Aditi","Anvi","Avni","Disha","Eva","Ishita","Kiara","Mahi","Meera",
    "Navya","Nisha","Pranavi","Riya","Shanaya","Siya","Tanvi","Trisha","Zara","Ananya",
    "Bhavya","Charvi","Esha","Gauri","Inaya","Jiya","Khushi","Lavanya","Nidhi","Pooja",
]
SURNAMES = [
    "Sharma","Verma","Kumar","Singh","Gupta","Reddy","Iyer","Patel","Mehta","Joshi",
    "Nair","Naidu","Shah","Rao","Pillai","Menon","Bose","Das","Sen","Roy",
    "Banerjee","Chatterjee","Mukherjee","Kapoor","Khanna","Malhotra","Chopra","Bhat",
    "Hegde","Pai","Shenoy","Kamat","Desai","Trivedi","Bhargava","Saxena","Mishra","Tiwari",
]
PARENT_TITLES = ["Sri", "Mr.", "Smt.", "Mrs."]
CITIES = ["Bengaluru", "Hyderabad", "Pune", "Chennai", "Mumbai", "Mysore"]
LOCALITIES = [
    "Jayanagar","Indiranagar","Koramangala","HSR Layout","Whitefield",
    "Banjara Hills","Madhapur","Kondapur","Andheri","Bandra","Powai",
    "Adyar","Anna Nagar","Velachery","Aundh","Baner","Wakad","Vijayanagar",
    "Rajajinagar","Malleshwaram",
]


# ---------- Class sizes (sums to 300) ---------- #
CLASS_SIZES = {
    "KG1": 18, "KG2": 22,
    "1": 28, "2": 28, "3": 30, "4": 28,
    "5": 28, "6": 26, "7": 24, "8": 24,
    "9": 22, "10": 22,
}
assert sum(CLASS_SIZES.values()) == 300, "class sizes don't sum to 300"


# ---------- Fee structure per class (annual ₹) ---------- #
FEE_STRUCTURES = {
    "KG1": dict(tuition_fee=18000, transport_fee=6000, books_fee=2000, uniform_fee=1500, other_fee=500),
    "KG2": dict(tuition_fee=20000, transport_fee=6000, books_fee=2200, uniform_fee=1500, other_fee=500),
    "1":   dict(tuition_fee=24000, transport_fee=7000, books_fee=3000, uniform_fee=1800, other_fee=800),
    "2":   dict(tuition_fee=26000, transport_fee=7000, books_fee=3200, uniform_fee=1800, other_fee=800),
    "3":   dict(tuition_fee=28000, transport_fee=7500, books_fee=3500, uniform_fee=2000, other_fee=1000),
    "4":   dict(tuition_fee=30000, transport_fee=7500, books_fee=3800, uniform_fee=2000, other_fee=1000),
    "5":   dict(tuition_fee=32000, transport_fee=8000, books_fee=4000, uniform_fee=2200, other_fee=1200),
    "6":   dict(tuition_fee=34000, transport_fee=8000, books_fee=4500, uniform_fee=2200, other_fee=1200),
    "7":   dict(tuition_fee=36000, transport_fee=8500, books_fee=5000, uniform_fee=2400, other_fee=1500),
    "8":   dict(tuition_fee=38000, transport_fee=8500, books_fee=5500, uniform_fee=2400, other_fee=1500),
    "9":   dict(tuition_fee=42000, transport_fee=9000, books_fee=6500, uniform_fee=2600, other_fee=2000),
    "10":  dict(tuition_fee=45000, transport_fee=9000, books_fee=7500, uniform_fee=2600, other_fee=2500),
}

# Approx age per class (years)
CLASS_AGE = {
    "KG1": 4, "KG2": 5,
    "1": 6, "2": 7, "3": 8, "4": 9,
    "5": 10, "6": 11, "7": 12, "8": 13,
    "9": 14, "10": 15,
}


# ---------- Generators ---------- #

def gen_aadhaar() -> str:
    return "".join(str(random.randint(0, 9)) for _ in range(12))


def gen_phone() -> str:
    return random.choice("6789") + "".join(str(random.randint(0, 9)) for _ in range(9))


def gen_dob(class_name: str) -> date:
    age = CLASS_AGE[class_name]
    today = date.today()
    base = today.replace(year=today.year - age)
    # Drift up to ±180 days for variety.
    return base - timedelta(days=random.randint(0, 360)) + timedelta(days=random.randint(0, 60))


def gen_admission_date(class_name: str) -> date:
    today = date.today()
    # Older students were admitted earlier.
    years_back = max(0, ["KG1","KG2","1","2","3","4","5","6","7","8","9","10"].index(class_name) - 1)
    yr = today.year - years_back
    return date(yr, 6, random.randint(1, 25))


def gen_name(gender: str) -> tuple[str, str]:
    first = random.choice(FIRST_M if gender == "M" else FIRST_F)
    surname = random.choice(SURNAMES)
    return first, surname


def gen_parent(surname: str, child_gender: str) -> str:
    # 60% father, 40% mother
    is_father = random.random() < 0.6
    title = "Mr." if is_father else "Mrs."
    first = random.choice(FIRST_M if is_father else FIRST_F)
    return f"{title} {first} {surname}"


def gen_address() -> str:
    city = random.choice(CITIES)
    locality = random.choice(LOCALITIES)
    no = random.randint(1, 600)
    return f"#{no}, {locality}, {city}"


def gen_last_year_dues() -> float:
    # ~70% nothing, ~30% a small carry-forward
    if random.random() < 0.70:
        return 0
    return float(random.choice([500, 1000, 1500, 2000, 2500, 3500, 5000, 7500]))


# ---------- Build the 300 rows ---------- #

def build_teachers() -> list[dict]:
    """A roster of 12 demo teachers spread across classes + subjects."""
    plan = [
        ("Sunita Iyer",    "Math",    "KG1,KG2,1,2",        True),
        ("Ramesh Sharma",  "English", "1,2,3,4",            False),
        ("Asha Reddy",     "Science", "3,4,5",              False),
        ("Karthik Menon",  "Math",    "5,6,7",              True),
        ("Priya Nair",     "Hindi",   "1,2,3,4,5",          False),
        ("Vijay Patel",    "Social",  "5,6,7,8",            False),
        ("Meera Bose",     "English", "5,6,7,8",            True),
        ("Anil Kapoor",    "Math",    "8,9,10",             False),
        ("Lakshmi Pillai", "Science", "6,7,8,9",            False),
        ("Suresh Khanna",  "Social",  "9,10",               False),
        ("Geetha Joshi",   "Hindi",   "6,7,8,9,10",         True),
        ("Naveen Rao",     "Science", "10",                 False),
    ]
    out = []
    for i, (name, subj, classes, can_front) in enumerate(plan, start=1):
        first = name.split(" ")[0].lower()
        out.append({
            "name": name,
            "email": f"{first}.{name.split(' ')[-1].lower()}@{EMAIL_DOMAIN}",
            "password": DEFAULT_TEACHER_PWD,
            "employee_id": f"NHST{i:03d}",
            "subject": subj,
            "classes_taught": classes,
            "qualification": random.choice(["B.Ed, M.A.", "M.Sc, B.Ed", "M.A., B.Ed", "Ph.D"]),
            "phone": "9" + "".join(str(random.randint(0,9)) for _ in range(9)),
            "can_do_front_office": can_front,
        })
    return out


def build_students() -> list[dict]:
    rows = []
    seq = 1
    for class_name, size in CLASS_SIZES.items():
        for i in range(size):
            section = "A" if i < size // 2 else "B"
            gender = random.choices(["M", "F", "O"], weights=[49, 49, 2])[0]
            first, surname = gen_name(gender if gender != "O" else random.choice(["M","F"]))
            row = {
                "admission_no":   f"NHS{seq:04d}",
                "name":           f"{first} {surname}",
                "student_class":  class_name,
                "section":        section,
                "aadhaar":        gen_aadhaar(),
                "dob":            gen_dob(class_name).isoformat(),
                "gender":         gender,
                "parent_name":    gen_parent(surname, gender),
                "phone":          gen_phone(),
                "address":        gen_address(),
                "last_year_dues": gen_last_year_dues(),
                "status":         "active",
                "admission_date": gen_admission_date(class_name).isoformat(),
            }
            rows.append(row)
            seq += 1
    return rows


def write_csv(rows: list[dict]) -> Path:
    CSV_DIR.mkdir(parents=True, exist_ok=True)
    cols = list(rows[0].keys())
    with open(CSV_PATH, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)
    return CSV_PATH


# ---------- HTTP helpers (stdlib only) ---------- #

def http(method: str, path: str, *, token: str | None = None,
         json_body: dict | None = None, multipart: tuple[str, bytes, str] | None = None):
    url = API + path
    body = b""
    headers = {"Accept": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    if json_body is not None:
        body = json.dumps(json_body).encode()
        headers["Content-Type"] = "application/json"
    elif multipart is not None:
        filename, data, mime = multipart
        boundary = "----nhsseed-" + "".join(random.choices("ABCDEF0123456789", k=16))
        body = (
            f"--{boundary}\r\n"
            f'Content-Disposition: form-data; name="file"; filename="{filename}"\r\n'
            f"Content-Type: {mime}\r\n\r\n"
        ).encode() + data + f"\r\n--{boundary}--\r\n".encode()
        headers["Content-Type"] = f"multipart/form-data; boundary={boundary}"

    req = urllib.request.Request(url, data=body if body else None, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            payload = r.read().decode()
            return r.status, json.loads(payload) if payload.strip().startswith(("[","{")) else payload
    except urllib.error.HTTPError as e:
        try: detail = json.loads(e.read().decode())
        except Exception: detail = {"error": e.reason}
        return e.code, detail


def banner(s: str): print(f"\n\033[36m{'─' * (len(s) + 2)}\033[0m\n\033[36m {s} \033[0m\n\033[36m{'─' * (len(s) + 2)}\033[0m")


# ---------- Main ---------- #

def main():
    banner("Generating 300 students")
    rows = build_students()
    write_csv(rows)
    by_class = {}
    for r in rows:
        by_class.setdefault(r["student_class"], 0)
        by_class[r["student_class"]] += 1
    print(f"  wrote {CSV_PATH.relative_to(ROOT)}  ({len(rows)} students)")
    for c in CLASS_SIZES:
        print(f"    Class {c:<3} : {by_class[c]:>3} students")

    banner("Connecting to API")
    code, info = http("GET", "/")
    if code != 200:
        print(f"  ✗ API unreachable at {API}")
        print( "    Start the app first with:  py run.py")
        sys.exit(1)
    print(f"  ✓ {info.get('name')} v{info.get('version')} reachable")

    banner("Logging in as Owner")
    code, t = http("POST", "/auth/login", json_body={"email": OWNER_EMAIL, "password": OWNER_PWD})
    if code != 200:
        print(f"  ✗ login failed: {t}"); sys.exit(1)
    token = t["access_token"]
    print(f"  ✓ logged in as {t['user']['email']}")

    banner("Uploading students CSV (upsert by admission_no)")
    with open(CSV_PATH, "rb") as f:
        data = f.read()
    code, res = http("POST", "/students/import",
                     token=token,
                     multipart=("seed_students.csv", data, "text/csv"))
    if code != 200:
        print(f"  ✗ import failed: {res}"); sys.exit(1)
    print(f"  ✓ created {res['created']}, updated {res['updated']}, errors {res['error_count']}")
    if res["errors"]:
        for e in res["errors"][:5]:
            print(f"    row {e['row']}: {e['error']}")

    banner("Setting up fee structures + applying to all classes")
    # Fetch existing structures so we don't duplicate.
    code, existing = http("GET", "/fee-structures", token=token)
    have = {(e["student_class"], e["academic_year"]): e["id"] for e in (existing if isinstance(existing, list) else [])}

    total_bills = 0
    for cls, fees in FEE_STRUCTURES.items():
        key = (cls, ACADEMIC_YEAR)
        if key in have:
            sid = have[key]
            print(f"  · class {cls:<3}: structure already exists (id={sid})")
        else:
            code, fs = http("POST", "/fee-structures",
                            token=token,
                            json_body={"student_class": cls, "academic_year": ACADEMIC_YEAR, **fees})
            if code != 200:
                print(f"  ✗ class {cls}: structure failed: {fs}"); continue
            sid = fs["id"]
            print(f"  ✓ class {cls:<3}: structure created (id={sid}, total ₹{sum(fees.values()):,})")

        code, ar = http("POST", f"/fee-structures/{sid}/apply", token=token)
        if code == 200:
            print(f"           → bills generated: {ar['created']}")
            total_bills += ar["created"]

    banner("Creating exams + marks (Term 1 + Half-yearly, 5 subjects each)")
    # Look up actual student IDs by admission_no so we attach marks correctly.
    code, all_students = http("GET", "/students", token=token)
    if code != 200:
        print(f"  ✗ couldn't fetch students: {all_students}"); sys.exit(1)
    by_class = {}
    for s in all_students:
        by_class.setdefault(s["student_class"], []).append(s)

    # Per-student "talent" — stable across exams, with small bump in Term 2.
    talent = {s["id"]: random.gauss(0, 12) for s in all_students}

    total_marks_saved = 0
    for cls, students in by_class.items():
        for ex_idx, ex in enumerate(EXAMS):
            code, exam = http("POST", "/exams",
                              token=token,
                              json_body={"name": ex["name"], "academic_year": ACADEMIC_YEAR,
                                         "student_class": cls, "date": ex["date"]})
            if code != 200:
                print(f"  ! class {cls} {ex['name']}: skipped ({exam})"); continue
            exam_id = exam["id"]

            # Class talent baseline drifts up for higher classes (older = more practiced).
            class_baseline = 60 + (["KG1","KG2","1","2","3","4","5","6","7","8","9","10"].index(cls)) * 1.2
            improvement = ex_idx * 1.5  # marks improve a bit by Half-yearly

            rows = []
            for s in students:
                for subj in SUBJECTS:
                    # Subject-specific affinity per student
                    subj_bias = random.gauss(0, 6)
                    raw = class_baseline + talent[s["id"]] + subj_bias + improvement \
                          + random.gauss(0, 4)
                    score = max(0, min(100, round(raw)))
                    rows.append({
                        "student_id": s["id"],
                        "subject": subj,
                        "marks_obtained": float(score),
                        "max_marks": 100.0,
                    })

            code, res = http("POST", f"/exams/{exam_id}/marks/bulk",
                             token=token,
                             json_body={"exam_id": exam_id, "rows": rows})
            if code == 200:
                total_marks_saved += res.get("saved", 0)
                print(f"  ✓ class {cls:<3} {ex['name']:<11} → {len(rows)} marks saved")
            else:
                print(f"  ! class {cls} {ex['name']}: {res}")

    banner("Creating teacher accounts (12 demo teachers)")
    teachers = build_teachers()
    teachers_created = 0
    for t in teachers:
        code, res = http("POST", "/teachers", token=token, json_body=t)
        if code == 200:
            teachers_created += 1
            print(f"  ✓ {t['name']:<22} ({t['employee_id']})  →  {t['email']} / {DEFAULT_TEACHER_PWD}")
        elif code == 400 and "already" in str(res).lower():
            print(f"  · {t['name']:<22} already exists")
        else:
            print(f"  ! {t['name']}: {res}")

    banner("Creating student logins (300)")
    code, all_students = http("GET", "/students", token=token)
    student_logins = 0
    if code == 200:
        for s in all_students:
            email = f"{s['admission_no'].lower()}@{EMAIL_DOMAIN}"
            # Check if already linked
            code2, _ = http("POST", "/auth/signup", json_body={
                "name": s["name"], "email": email,
                "password": DEFAULT_STUDENT_PWD,
                "role": "student", "admission_no": s["admission_no"],
            })
            if code2 == 200:
                student_logins += 1
        print(f"  ✓ created {student_logins} student logins (skipped any already linked)")
        print(f"    pattern: {{admission_no}}@{EMAIL_DOMAIN}  /  {DEFAULT_STUDENT_PWD}")
        print(f"    e.g.    nhs0001@{EMAIL_DOMAIN}  /  {DEFAULT_STUDENT_PWD}")

    banner("Seeding sample assignments")
    SAMPLE_ASSIGNMENTS = [
        ("3", "English", "Story Writing", "Write a 200-word story about your favorite animal.", 5),
        ("5", "Math",    "Times Tables Practice", "Memorize 6 to 12 times tables. Quiz on Monday.", 7),
        ("7", "Science", "Lab Report — Plant Cell", "Draw and label a plant cell. Submit before due date.", 10),
        ("9", "Social",  "Map Work — India States", "Identify and label all 28 states with capitals.", 5),
        ("10","Math",    "Trigonometry Worksheet", "Complete problems 1-15 from chapter review.", 5),
    ]
    # Pick the first teacher for any class as the author
    code, teacher_list = http("GET", "/teachers", token=token)
    teachers_by_class = {}
    if code == 200:
        for t in teacher_list:
            for c in (t.get("classes_taught") or "").split(","):
                teachers_by_class.setdefault(c.strip(), []).append(t)

    asg_created = 0
    today = date.today()
    for cls, subj, title, desc, mx in SAMPLE_ASSIGNMENTS:
        teachers_for = teachers_by_class.get(cls, [])
        if not teachers_for:
            continue
        teacher = teachers_for[0]
        # Need the teacher's user token to create — easier: log in as that teacher
        code, t_login = http("POST", "/auth/login",
            json_body={"email": teacher["email"], "password": DEFAULT_TEACHER_PWD})
        if code != 200:
            continue
        t_token = t_login["access_token"]
        due = (today + timedelta(days=random.randint(7, 30))).isoformat()
        code, _ = http("POST", "/assignments", token=t_token, json_body={
            "student_class": cls, "subject": subj,
            "title": title, "description": desc,
            "due_date": due, "max_marks": float(mx),
        })
        if code == 200:
            asg_created += 1
            print(f"  ✓ class {cls} {subj}: {title}")

    banner("Done")
    print(f"  • CSV source file  : {CSV_PATH}")
    print(f"  • students loaded  : 300")
    print(f"  • fee bills made   : {total_bills}")
    print(f"  • marks recorded   : {total_marks_saved}")
    print(f"  • teachers created : {teachers_created}")
    print(f"  • student logins   : {student_logins}")
    print(f"  • sample asgs.     : {asg_created}")
    print()
    print(f"  Open http://localhost:3000 and sign in:")
    print(f"    Owner    : {OWNER_EMAIL} / {OWNER_PWD}")
    print(f"    Staff    : staff@{EMAIL_DOMAIN} / staff123")
    print(f"    Teacher  : sunita.iyer@{EMAIL_DOMAIN} / {DEFAULT_TEACHER_PWD}  (and others)")
    print(f"    Student  : nhs0001@{EMAIL_DOMAIN} / {DEFAULT_STUDENT_PWD}  (any nhs0001..nhs0300)")


if __name__ == "__main__":
    main()
